export const PUBLISHED_ARTICLES = "PUBLISHED_ARTICLES";
export const USER_ARTICLES = "USER_ARTICLES";
export const ADD_FILTER_TAG = "ADD_FILTER_TAG";
export const REMOVE_FILTER_TAG = "REMOVE_FILTER_TAG";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const USER_AUTH = "USER_AUTH";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
